### ISSUE TITLE
Position on page after submitting hosting form

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratchjr-website#115]
After submitting hosting form, you are located at the bottom of the page and have to scroll up to see the content. Ideally, you would get re-positioned at the top of the page.

To repro, go to `/outreach/host` and submit the form:
<img width="1083" alt="screen shot 2017-10-10 at 1 33 27 pm" src="https://user-images.githubusercontent.com/1320456/31401068-a9149f56-adbf-11e7-8b15-1e68685e5b56.png">

Happens in both Chrome + Win 7 & Chrome + Mac OS El Capitan.

**Comment by chrisgarrity** [comment]
Submitted pr: https://github.com/LLK/scratchjr-website/pull/117
includes code to reset the page to the top after the form submission.

**Comment by chrisgarrity** [comment]
Fixed in https://github.com/LLK/scratchjr-website/pull/117

**Comment by jwzimmer** [comment]
This now works! After submitting the form I am taken to the top of the following page.

Tested in Chrome & Safari, Mac OS El Capitan, Staging.
