### ISSUE TITLE
FAQ page missing a hyphen 

### ISSUE THREAD

**Issue by vutondesign** [LLK/scratchjr-website#127]
> this new book is an easy-to-use, **hands on** resource for parents and educators alike to teach children how to code with ScratchJr. 

Should be...

> this new book is an easy-to-use, **hands-on** resource for parents and educators alike to teach children how to code with ScratchJr.

**Comment by redmangospros** [comment]
I can do this.

**Comment by vutondesign** [comment]
Whoops, I forgot that this was marked as ``help-wanted`` a while ago, so I've gone and taken it as I meant to.
