### ISSUE TITLE
Add ScratchJr book and coding cards to the website

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr-website#216]
add the ScratchJr book and coding cards as news items on the home page.

Book news item:
_The Official ScratchJr Book_ is the perfect companion to the app and makes coding easy and fun for all.
Link _The Official ScratchJr Book_ to https://www.amazon.com/Official-ScratchJr-Book-Help-Learn/dp/1593276710/
Cards new item:
The _ScratchJr Coding Cards_ are a deck of 75 activity cards covering fun and exciting projects designed to educate young children with ScratchJr.
Link _ScratchJr Coding Cards_  to https://www.amazon.com/ScratchJr-Coding-Cards-Creative-Activities/dp/1593278993/

**Comment by thisandagain** [comment]
If anyone else would like to take this issue we would greatly appreciate it! :-)

**Comment by IamTregsthedev** [comment]
I can. You mean index.html or the jsx files?

**Comment by chrisgarrity** [comment]
@IamTregsthedev this is an update to the news section in the `index.jsx`:  https://github.com/LLK/scratchjr-website/blob/83bf910a07260a008483804d703531a12992e746/src/views/index/index.jsx#L86

There are three items. We should remove the last two, and then add the two new items before the one that is left.

**Comment by IamTregsthedev** [comment]
Thanks. What do i add. I'm know jsx but not to much, but want to help

**Comment by chrisgarrity** [comment]
@IamTregsthedev I added the text for the new news items to the original description above. Just use the current news items as a template for what needs to be done.

**Comment by IamTregsthedev** [comment]
Okay! :) Thanks!
