### ISSUE TITLE
Fix load time of Teach page

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr-website#225]
The 'Teach' section of the website takes a long time to load. 

The site currently loads all of the subsections of a page to make switching tabs within the page fast. Unfortunately the teach section has become large enough that it takes noticeably longer to load. It should probably be split up into separate pages.

**Comment by R4356th** [comment]
@chrisgarrity, I could help if you told me how you want the section to be split. My suggestion would be to list them on the Teach page; or you might want to have a better footer.

**Comment by chrisgarrity** [comment]
@R4356th we don't want to change the design, just how it loads. I think if you use the network browser developer tools, you'll see that when you load the teach page there is one large bundle for everything for the activities, curricula and assessments even though it's only showing the activities. Instead there should be three separate bundles for the activities, curricula and assessments, so only the section that is visible needs to be loaded. We're using react-router on this website, so it would need to work in a react-router compatible way.

**Comment by R4356th** [comment]
@chrisgarrity, so do you mean that you want to split them to different pages (or sections) and keep activities as it is now?

**Comment by chrisgarrity** [comment]
If you look at the teach jsx file, we use react-router (an older version BTW). The 'root' path, automatically redirects to the activities section:
https://github.com/LLK/scratchjr-website/blob/f6049f7bc840ba3a30116961e264d1f98314cd72/src/views/teach/teach.jsx#L41-L50
But all of the sections are getting loaded before the page displays, so it's slow to load. E.g. switching to curriculum is almost instant.

Instead of having the teach page use react-router and load all the sections, there should be individual sections. And the activites tab is the default.

**Comment by chrisgarrity** [comment]
@R4356th just a note, there's some new discussion on the team of replacing the teach section with something else. For now I've removed the help wanted label, and I'm closing the issue. If we don't replace the section it may get reopened.
