### ISSUE TITLE
Revise Credits and Footer

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr-website#282]
### Expected Behavior

Revise the footer to read:

> **ScratchJr** is a collaboration between the DevTech Research Group at Tufts University, and the Scratch Foundation.

On the About...Info page. In the "Who created ScratchJr?" section
Change:

> ScratchJr is a collaboration between the ... The Android version

to

> ScratchJr was developed by the ... The first Android version

New "Who Helped to Translate ScratchJr?" section:
ScratchJr has been translated into more than a dozen languages with the generous help of volunteer translators from around the world. Special thanks go to the translators who helped with our first translation into Spanish: Teresa Martínez Pérez, childhood education student; Marta Bonet Garrosa, Manuela Lara Lara, and Lidia Piñeiro Cordero, of Editorial Santillana; Sergio Antolinez, CEO of Tecnoaprendo; and Luisa María Palacios Maroto.

**Comment by chrisgarrity** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ScratchJr website updates](https://trello.com/c/vIJ6Ehur/36-scratchjr-website-updates)

**Comment by deepankarmalhan** [comment]
Fixed
