### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr-website#318]
### Expected Behavior
Privacy policy on the website, linked to from the app and play stores, should match the [privacy policy](https://docs.google.com/document/d/1YLE6Cl94nKjKpe5vpqvUx_rDU1UVBQRK/edit) in the app.

The new privacy policy is clearer and is in line with current best practices. We are not actually changing any of the app data collection or reporting, so the privacy policy on the website can be updated ahead of the app.

**Comment by deepankarmalhan** [comment]
Fixed
