### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr-website#319]
With recent updates to ChromeOS we have removed the Chrome Web App (extension) version of ScratchJr from the Chrome Web Store. It is no longer functional.

As a result the information on the website is incorrect and needs to be updated. [Chromebook rephrase document](https://tufts.app.box.com/s/le4lpgueqdkqz8j8akyuolk1432dfyed) contains the new text, including links and formatting. The text is also included below for convenience.

**Page: About -> Info**
Section: What is ScratchJr
Current Text: “ScratchJr is available as a free app for both iPad and Android tablets. For more information about ScratchJr, see scratchjr.org.”
Replacement Text: “ScratchJr is available as a free app for iPads, Android tablets, and Chromebooks.”

**Page: About -> FAQ**
Current Text: 
Will ScratchJr run on my Chromebook?

In March 2016 a version was released for Chromebooks. You can find ScratchJr in the Chrome Web Store.This version was built from the Android version. We have had to remove some features, such as sharing, due to differences between Android and Chrome OS. We are providing this application AS IS. If you run into problems, please do let us know, but we cannot promise that we will fix bugs in this version.If you have a Chromebook that can install Android apps from the Play store, we recommend that you install that version.

Replacement Text:
Will ScratchJr run on my Chromebook?

The android version of ScratchJr that is available on the Google Play store will run on all Chromebooks with the capability of running android apps. This will work on both touchscreen and non-touchscreen Chromebooks.

### Other FAQ changes:
All content below is the new content

**Will ScratchJr run on my iPad or tablet?**
ScratchJr runs on both iPads and Android tablets. ScratchJr can be installed on any iPad running iOS 9.3 or greater. Previous versions of ScratchJr running on earlier versions of iOS will not receive any more updates. ScratchJr can also be installed on any Android tablet, 7 inches or larger, that are running Android 5.0 (Lollipop) or greater. You may be able to install earlier versions of ScratchJr from the Google Play store that are compatible with earlier versions of Android, but they are no longer supported and are not receiving updates.
We recommend iPads running iOS 11 or higher and Android tablets running Android 7 or higher.

**Can I share a ScratchJr project from one tablet to another?**
If you are running ScratchJr version 1.2 or greater, you can share projects via email. On iPads you can also share by AirDrop. To access the sharing options, go to the Project Information page by tapping on the yellow button in the top-right corner of the ScratchJr editor.

Also, remove the section for:
**I have an Android tablet that is running 4.2+, but Google Play still says that my device is incompatible.**

**Will ScratchJr be available in other languages?**
Currently ScratchJr supports 20 languages including English, ... (keep the rest the same)

Change the Last Updated text.

**Comment by deepankarmalhan** [comment]
Fixed
