### ISSUE TITLE
On hover darken nav bar button

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratchjr-website#99]
This will make it easier for people to see the difference between the button the user is trying to press and the normal button.

**Comment by GreenBayRules** [comment]
@thisandagain Is it okay if I make a PR for this?

**Comment by thisandagain** [comment]
Could you provide a quick mockup of what you think it would look like?

**Comment by GreenBayRules** [comment]
@thisandagain Sure, this would be a screenshot of when the mouse is on the "Outreach" button:
![image](https://user-images.githubusercontent.com/11379161/32080994-9529a9f0-ba67-11e7-8285-09fb9772bdcc.png)

**Comment by thisandagain** [comment]
Looks good to me! Any thoughts @chrisgarrity ?

**Comment by GreenBayRules** [comment]
I can make a pull request for this if the help-wanted tag comes up.

**Comment by chrisgarrity** [comment]
@GreenBayRules @thisandagain sounds good to me too - adding the help-wanted tag :)

**Comment by GreenBayRules** [comment]
Thanks, I'll do this one.

**Comment by GreenBayRules** [comment]
Okay I have made a pull request #125 @thisandagain
